name: Build

on:
  push:
  workflow_dispatch:

jobs:
  build:
    runs-on: windows-2022
    steps:
      - name: Checkout self
        uses: actions/checkout@v4

      - name: Checkout librime
        uses: actions/checkout@v4
        with:
          repository: rime/librime
          ref: refs/tags/1.11.2
          path: librime

      - name: Setup msvc
        uses: ilammy/msvc-dev-cmd@v1
        with:
          arch: x64
          toolset: 14.29
          sdk: 10.0.19041.0

      - name: Modify
        run: |
          Move-Item -Path .\build.bat -Destination .\librime\build.bat -Force

      - name: Fetch deps
        run: |
          git submodule update --init --recursive

      - name: Install boost
        uses: MarkusJx/install-boost@v2
        with:
          boost_version: 1.77.0
          boost_install_dir: "C:/boost_1_77_0"
          platform_version: 2019
          toolset: msvc
          link: static

      - name: Build
        working-directory: librime
        env:
          BOOST_ROOT: "C:/boost_1_77_0"
        shell: cmd
        run: |
          build.bat

      - name: Archive binary
        uses: actions/upload-artifact@v4
        with:
          name: librime
          path: |
            librime/builds/*/bin/*.exe
            librime/builds/*/bin/*.dll
